Cargo.lock, src/config.rs
Add a call to _create_dir_all_ to fix panic if the config parent dir doesn't exist.
+ change to cargo.lock => outdated, project renamed from **duralumin** to **dura** ?
Nb: sorry, rustfmt applied on commit
=> Fix panic if config dir inexistant: create_dir_all

README.md
Addresses [Issue #26](https://github.com/tkellogg/dura/issues/26)
* Added `brew install rust` since this was required to provide the cargo executable.
* Added `git clone` example to ease installation steps
* Added instruction to navigate to repository source base directory.
* Added option for using the local git client for fetching dependencies in the event of a failure with a link to the cargo documentation that references this configuration option.
=> Hombrew install instruction updates to README

README.md
A tiny change, but it means you can just copy-paste the install instructions even if you don't have a GitHub SSH key configured on this machine 🙂
=> Switch installation example repo URLs to HTTPS

scripts/dura.fish
Before doing any changes to the Rust code, I wanted to get an idea of how we want these scripts to work.
The `dura.fish` shell script can:
1. Read `repos` and `pollingSeconds` from `config.json`
2. Start a repo watcher in the background using those settings
3. Watch for changes in `config.json` and restart the repo watcher on any change
4. Ensure only one instance of the script is running (helpful if you want to add it in `conf.d` as a script that runs on each shell startup)
If we settle on a fish shell script, I can then try to convert that to POSIX bash/zsh and add some basic `dura install` command.
=> Add fish integration

scripts/dura.fish
`command -v` is a better choice here than `which` because many
operating systems have a `which` that doesn't set an exit status,
causing this to return true incorrectly. Additinally, which launches
an external process, so `command -v` will be cheaper and POSIX
complient.
See
https://stackoverflow.com/questions/592620/how-can-i-check-if-a-program-exists-from-a-bash-script
for more details
=> Replace which with command -v

tests/end_to_end_test.rs
Currently, the `start_serve_with_null_pid_in_config` actually writes to `~/.config/dura` instead of the temporary directory, like the other tests.
This patch makes it use a temporary directory for the config, like other tests. It also reverses an assert, because previously the test wouldn't load the config file at all (since it tried to load from the temporary directory, and not from home).
=> Make test use tmpdir for saving config

README.md
Updates README branch name when dura is backing up. Default branch is changed from `dura-{}` to `dura/{}` after #48
=> Update default branch on README.md

src/main.rs
Leading on from the conversion to Clap, this makes the CLI improvements discussed in #51. These are as follows:
- The program will still default to the CWD, but you can now optionally specify a directory for watch/unwatch/snapshot using a positional arg
- Include, exclude and maxdepth flags have been added when watching a directory to control the recursive behaviour. Multiple comma-separated include/exclude paths can be specified.
- The `logfile` arg for serve has been changed from positional to a flag
```
dura watch --help                                                           dura-watch 
Add the current working directory as a repository to watch.
USAGE:
dura {watch, --watch, -W} [OPTIONS] [directory]
ARGS:
<directory>    The directory to watch. Defaults to current directory [default: …
```
=> CLI Improvements

Cargo.toml, src/config.rs, src/git_repo_iter.rs, src/lib.rs, src/poller.rs, tests/snapshots_test.rs, tests/startup_test.rs, tests/util/dura.rs, tests/util/git_repo.rs, tests/watch_test.rs
`poller::process_directory` became recursive in #49. This function did 2 things:
1. Recursively list out all Git repos
2. Process them
This change separates these two responsibilities. This gives us a lot of flexibility, like the ability to see query the watched directories. We used to just look directly at the Config object, but since it was refactored we lost that ability. This gains that ability back.
@JakeStanger take a peek
=> Refactor: Extract GitRepoIter

Cargo.lock, Cargo.toml, src/config.rs, src/database.rs, src/git_repo_iter.rs, src/lib.rs, src/main.rs, src/poller.rs, tests/startup_test.rs, tests/util/dura.rs, tests/watch_test.rs
Associated: #28 
The repo config and runtime database are now separate. The config is stored in `.config/dura/config.toml` and the runtime database (PID) is stored in .cache/dura/runtime.db (in JSON format).
The `home` package has been replaced with `dirs` [(crate)](https://crates.io/crates/dirs) for better support for user directories. This means getting the config/cache dir should always work across OS.
The `DURA_HOME` env var has been replaced with `DURA_CONFIG_HOME` and `DURA_CACHE_HOME` to accommodate the change.
A couple of flaky runtime tests have also been fixed to use `HashSet` instead of `Vec`, as collecting the repo `HashMap` keys didn't guarantee the same order and could sometimes incorrectly fail.
Example runtime DB:
```json
{"pid":34143}
```
Example config file:
```toml …
```
=> Split config file and runtime DB

.github/workflows/build.yaml
Hi,
This adds the commit sha256 sum to the end of the artifact names to differentiate between versions.
BTW, do you have any plans for a release schedule?
I can create a workflow for automatic releases.
I also added a pre-requisite for that in this commit: (https://github.com/tkellogg/dura/commit/1a09368649347e7ebbcfb40d6ed96a3f1f158fff)
Thanks
=> Add commit sha to build artifacts

Cargo.lock, Cargo.toml, src/config.rs, src/git_repo_iter.rs, src/main.rs, src/poller.rs, src/snapshots.rs, tests/snapshots_test.rs, tests/startup_test.rs, tests/util/dura.rs, tests/util/git_repo.rs, tests/util/workspace.rs, tests/watch_test.rs
Closes #21 
Previously, dura uses the latest commit to determine commit author and email, this PR aims to change the way dura determines this.
This PR allow specifying commit author and email in config file by adding 2 field in config:
- `commit_author`: preferred author for dura commits
- `commit_email`: preferred email for dura commits
When signing commit, dura will prefer the following order of preference when choosing author/email:
1. Dura config
2. Git config
3. Defaults to `author: dura`, `email: dura@github.io`
---
Planning to add more knob to allow user to choose between preference 2 and 3
=> feat: Use dura config and git config for commit signature

.github/workflows/build.yaml, Cargo.lock, Cargo.toml, tests/snapshots_test.rs, tests/util/dura.rs, tests/util/git_repo.rs
Tests broke in #66 but we didn't catch it because our CI/CD pipeline
doesn't run cargo test. This also enables tests on all platforms.
Ping @JakeStanger 
closes #72
=> Fix tests: write runtime db

.editorconfig, .github/workflows/build.yaml, src/config.rs, src/database.rs, src/git_repo_iter.rs, src/main.rs
Brings us closer to resolving #1.
Fixes all Clippy errors in the code-base and requires Clippy to find no problems for builds to pass.
Also refactors the CI workflow to use a matrix and avoid needing to maintain 3 separate near-identical jobs.
=> Fix clippy errors, add clippy to CI

src/main.rs, src/poller.rs, tests/startup_test.rs, tests/util/daemon.rs, tests/util/dura.rs, tests/util/mod.rs
I noticed that startup tests fail on very slow machines, like the build hosts. I also hate that there's a 6 second `thread::sleep`. This PR fixes both of those problems. Tests run in <1s.
To do this, I created `Daemon`, that sets up a mpsc (technically an spsc) channel that sends each line of stdout (from `dura serve`) as a message to the test. This lets tests do a `read_line` to wait until output is printed, or do it twice to wait for the first snapshot event. It's a great way to communicate between parent and child processes.
=> Fix test stability & speed

src/config.rs, src/database.rs, src/main.rs
Replaces some `unwrap` calls with `expect` calls to panic with more user-friendly messages. In the future we could look to implement better error handling, but since this runs as a daemon anyway, fancy error output is a nice-to-have. I think this should be enough to resolve #1.
There are still several `unwraps` in the code that I've chosen to leave as such, as they *should* cause a panic (things like failing to serialize a struct).
=> refactor: mildly improve error handling

.github/workflows/build.yaml, src/config.rs, src/database.rs, src/main.rs, tests/startup_test.rs, tests/util/daemon.rs, tests/util/dura.rs, tests/util/mod.rs
Handle and print more readable error messages on `capture` fail rather than panicking.
=> Show error message on `capture` fail

src/config.rs, src/database.rs
`dirs::config_dir()` is not always at `~/.config`. Re-written the comment for dura config home to describe this better.
See for reference https://docs.rs/dirs/4.0.0/dirs/fn.config_dir.html
=> chore: rewrite comment on dura config home

CONTRIBUTING.md, scripts/pre-commit.sh, src/lib.rs, src/main.rs, src/metrics.rs
This adds a `dura metrics --input {log file}` subcommand that captures the logs, filters it to just snapshots, and enriches it with useful Git info that's not in the logs:
* Number of lines `+`/`-`
* List of files changed
Sample output:
```
{"base_hash":"a799ffdedac9bfadd249de2f81f835a3fd80154c","commit_hash":"eff2ad3ed90e99603fc4ab6e64a7634bd6f0778d","deletions":2,"dura_branch":"dura/a799ffdedac9bfadd249de2f81f835a3fd80154c","files_changed":["src/main.rs"],"insertions":2,"latency":0.017979679629206657,"num_files_changed":1,"repo":"/Users/timkellogg/code/dura","time":"2022-01-23T07:13:34.805380+00:00"}
{"base_hash":"0c8340fa18cee96aba22629ef53b0412b3165bad","commit_hash":"c1b6c692646509ad8ddf389fb61aa02588dba706","deletions":1,"dura_branch":"dura/0c8340fa18cee96aba22629ef53b0412b3165bad"," …
```
=> Added metrics formatter

README.md
I published dura to crates.io.
Now can Install with `cargo install dura`!
=> Update for new install way!

CONTRIBUTING.md
`end_to_end_test.rs` is renamed to `startup_test.rs` after #65
=> chore: update test link on contributing docs

Cargo.lock, Cargo.toml, src/config.rs, src/database.rs, src/log.rs, src/poller.rs
I noticed that, when I'm not coding, dura consumes ~10% of CPU on one of my laptops. I want to do a better job of quantifying it before I dive into a larger project of reducing it.
This aggregates latency and only emits a log line every X minutes (currently const 10 minutes, I want to bump it up to 60 minutes before this is merged).
=> [Duralite] Latency metrics around scanning

Cargo.lock, Cargo.toml, scripts/pre-commit.sh, src/lib.rs, src/main.rs, src/poll_guard.rs, src/poller.rs, tests/poll_guard_test.rs, tests/snapshots_test.rs, tests/util/daemon.rs, tests/util/macros.rs, tests/util/mod.rs
The current version performs a `git commit` on every repository every 5 seconds. If nothing changed, it simply has no effect. This strategy is eating up sometimes 10-20% of my CPU (on a poor dev machine), due to the massive amount of hashing needed to commit so many repositories.
This change creates an optimization by tracking file changed timestamps and comparing them against last commit timestamps. To do this, we have to traverse all files in each repository, which `git commit` is doing anyway. The big difference is that we only need to traverse to the inode (directory) for the file timestamp entries, so it should be significantly faster.
It has been suggested to use the `notify` crate to be notified of file changes. The trouble here was a global limit on file descriptors that can be …
=> Optimization: Check file timestamps

Cargo.lock, Cargo.toml, src/main.rs
Simply checking the uid and euid to check if the user is root and just not checking on windows
(previous pr got removed because of discarding commit, sorry)
=> Do not allow to run dura as root
