README.md

Hello! I created a PKGBUILD for dura and put in on the aur so anyone using arch can simply install and build it themselves through pacman for easier management.

Update README to include arch instillation

---

README.md
src/main.rs

Added section about `dura kill` to the README file, and added a
documenting comment to the function `kill` in main.rs
Issue #16

Improve documentation of `dura kill` command

---

src/config.rs
src/log.rs
src/main.rs
src/poller.rs
src/snapshots.rs

This helps towards #1, although `std::env::home_dir()` is still being used.

Fix clippy issues

---

Cargo.lock
Cargo.toml
src/config.rs

Use home::home_dir instead of std::env::home_dir

---

README.md

I'm able to install and run on Windows 10

Added windows install instructions

---

README.md

As per https://github.com/tkellogg/dura/issues/25.

Document `find | xargs` initial setup workaround

---

.gitignore

To see even more rules check out https://www.toptal.com/developers/gitignore/api/rust

Added additional rules for rust to the .gitignore

---

src/config.rs
src/main.rs

Added an unwatch command as described by #41 
Also added a few messages to the watch command and a check to see if the directory was already being watched.

Add unwatch command

---

Cargo.lock
Cargo.toml
src/config.rs
src/lib.rs
src/log.rs
src/logger.rs
src/main.rs
src/poller.rs

WIP #30 
Currently logs to stdout only. Will add a flag for logfile after this. 
Sample logging 
What do you think @tkellogg ?

feat: logging using tracing crate 

---

src/snapshots.rs
tests/snapshots_test.rs

This PR:
Please bear with me, it's the first time I'm doing Rust and it's my first Rust PR too !

#47: Update default branch name

---

flake.lock
flake.nix

Hi,
I'm using those flake files to build a development environment for people using Nix.
Let me know if you're ok to include those files in the project (those could be used in Github actions to build the package automatically too)

Add flake files for development on Nixos.

---

src/logger.rs
tests/end_to_end_test.rs
tests/snapshots_test.rs
tests/util/dura.rs
tests/util/git_repo.rs
tests/util/mod.rs

This PR fixes warnings and Clippy lints across the entire codebase.

Fix warnings/lints

---

README.md
src/main.rs

fix: Minor typo

---

.github/CODEOWNERS
.github/dependabot.yml
.github/settings.yml
.github/workflows/build.yaml
.github/workflows/upgrade-flakes.yaml

ci: Enable github actions.

---

src/main.rs

#30 
This PR enables users of `dura serve` to specify a file for the logs. 
```
dura-serve
Starts the worker that listens for file changes. If another process is already running, this will do
it's best to terminate the other process.
USAGE:
dura {serve, --serve, -S} [logfile]
ARGS:
<logfile>    Sets custom logfile. Default is logging to stdout
OPTIONS:
-h, --help    Print help information
```` 
Current behavior 
1. If no log file is specified, stdout will be used for logging. 
2. If the logfile does not exist it will be created else the logs will be appended to the existing file.
3. The process will exit with an error to stderr if it is unable to open the logfile.

feat: Enable loging to a file

---

.github/workflows/build.yaml

This will upload the compiled binary to Github actions.

Add upload-artifact to build script

---

src/snapshots.rs

Addresses #58
This PR allows creating branch lazily

feat: lazy branch creation

---

Cargo.lock
Cargo.toml
src/main.rs

Updated cargo.toml to use clap V3.1.6, and modified main.rs to remove deprecated functionality.

UPDATE: Modified to  use clap V3.1.6

---

README.md

I don't type line break in cargo installation instruction lol

Add line break to readme cargo git.

---

Cargo.lock
Cargo.toml
src/main.rs

Upgrading clap to 4.0 with new functions and types introduced(#129)
Main points
- takes_value() -> num_args(1)
- value_of -> get_one
- values_of -> get_many
- version and default value now takes custom IntoResettable Type

Upgrade clap to 4.0 - Fixing #129
